# vim: set ft=sh ts=4 sw=4 sts=-1 noet:
# This file will be interpreted by /bin/bash.


################################################
# Disk configuration

function disk_configuration() {
	create_classic_single_disk_layout swap='2GiB' type='efi' luks='false' root_fs='ext4' '/dev/disk/by-id/scsi-0Verge.iotier1_drive2' ;
}


################################################
# System configuration

HOSTNAME='relayTemplate.smtp.xxx'
TIMEZONE='Europe/Copenhagen'
KEYMAP='us'
KEYMAP_INITRAMFS='us'

LOCALES='en_US.UTF-8 UTF-8'
LOCALE='en_US.utf8'

SYSTEMD_NETWORKD='true'
SYSTEMD_NETWORKD_INTERFACE_NAME='en*'
SYSTEMD_NETWORKD_DHCP='true'
SYSTEMD_NETWORKD_ADDRESSES='192.168.1.100/32'
SYSTEMD_NETWORKD_GATEWAY='192.168.1.1'
SYSTEMD_INITRAMFS_SSHD='false'


################################################
# Gentoo configuration

PORTAGE_SYNC_TYPE='git'
PORTAGE_GIT_FULL_HISTORY='false'
PORTAGE_GIT_MIRROR='https://anongit.gentoo.org/git/repo/sync/gentoo.git'
GENTOO_MIRROR='https://mirror.leaseweb.com/gentoo'
GENTOO_ARCH='amd64'
GENTOO_SUBARCH=''
STAGE3_VARIANT='systemd'
STAGE3_BASENAME="stage3-$GENTOO_ARCH-$STAGE3_VARIANT"
STAGE3_BASENAME_CUSTOM=$([[ $STAGE3_VARIANT == *x32* ]] && echo "stage3-systemd" || echo "stage3--systemd")
USE_PORTAGE_TESTING='false'
SELECT_MIRRORS='false'
SELECT_MIRRORS_LARGE_FILE='false'
SYSTEMD=$([[ $STAGE3_VARIANT == *systemd* ]] && echo "true" || echo "false")
MUSL=$([[ $STAGE3_VARIANT == *musl* ]] && echo "true" || echo "false")


################################################
# Additional (optional) configuration

ADDITIONAL_PACKAGES=(  "app-admin/monit" 
 "app-admin/monit"
 "app-admin/lsyncd"
 "app-emulation/qemu-guest-agent"
 "app-misc/jq"
 "app-misc/mc" 
 "app-misc/tmux"
 "app-portage/cpuid2cpuflags"
 "dev-libs/cyrus-sasl"
 "dev-perl/App-cpanminus"
 "dev-util/dialog"
 "mail-filter/opendkim"
 "mail-mta/postfix"
 "net-analyzer/fail2ban"
 "net-dns/bind-tools"
 "net-dns/dnsmasq"
 "sys-block/io-scheduler-udev-rules"
 "sys-fs/dosfstools"
 "sys-fs/xfsprogs"
 "sys-process/htop"
)
ENABLE_SSHD='true'
ENABLE_BINPKG='false'
KERNEL_TYPE='bin'
ROOT_SSH_AUTHORIZED_KEYS=''


#XPL_PATCH this is to be ran as a hook before configuring portage
before_configure_portage(){
    local makeconf="/etc/portage/make.conf"

    # Make sure the file exists
    if [[ ! -e "$makeconf" ]]; then
        echo "Creating $makeconf"
        touch "$makeconf" || { echo "Cannot create $makeconf"; return 1; }
    fi

    # Backup
    cp -a "$makeconf" "${makeconf}.bak-$(date +%Y%m%d%H%M%S)" || {
        echo "Failed to back up $makeconf"
        return 1
    }

    # COMMON_FLAGS
    if grep -qE '^COMMON_FLAGS=' "$makeconf"; then
        sed -i 's/^COMMON_FLAGS=.*/COMMON_FLAGS="-march=native -O2 -pipe"/' "$makeconf"
    else
        echo 'COMMON_FLAGS="-march=native -O2 -pipe"' >>"$makeconf"
    fi

    # MAKEOPTS
    if grep -qE '^MAKEOPTS=' "$makeconf"; then
        sed -i 's/^MAKEOPTS=.*/MAKEOPTS="-j8 -l9"/' "$makeconf"
    else
        echo 'MAKEOPTS="-j8 -l9"' >>"$makeconf"
    fi

    # ACCEPT_LICENSE
    if grep -qE '^ACCEPT_LICENSE=' "$makeconf"; then
        sed -i 's/^ACCEPT_LICENSE=.*/ACCEPT_LICENSE="*"/' "$makeconf"
    else
        echo 'ACCEPT_LICENSE="*"' >>"$makeconf"
    fi


    #LSYNCD (select which LUA to use)
    mkdir -p /etc/portage/package.use
    echo "app-admin/lsyncd LUA_SINGLE_TARGET: lua5-4" > /etc/portage/package.use/lsyncd
}

#XPL_PATCH recreate the gentoo repos dir before the emerge git sync
after_download_stage3() {
    mkdir -p /var/db/repos/gentoo
}

#XPL_PATCH save the cpu flags
after_install() {
   einfo 'after install'
   echo "*/* $(cpuid2cpuflags)" > /etc/portage/package.use/00cpu-flags
}

################################################
# Prove that you have read the config

I_HAVE_READ_AND_EDITED_THE_CONFIG_PROPERLY=true
